- name: Get system info
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print system information
      debug:
        msg:
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "CPU: {{ ansible_processor }}"
          - "Memory: {{ ansible_memtotal_mb }} MB"

